/**
 * Stable error codes for HLS remote imports (§25 of the feature spec).
 *
 * Every code here maps to a user-facing error message that never contains
 * internal IPs, local paths, stack traces, signed URLs, or secrets. The codes
 * are stable strings — the frontend keys UI behavior off the code, not the
 * message.
 */
export const HLS_ERROR_CODES = {
  HLS_DISABLED: 'HLS_DISABLED',
  HLS_INVALID_MANIFEST: 'HLS_INVALID_MANIFEST',
  HLS_MANIFEST_TOO_LARGE: 'HLS_MANIFEST_TOO_LARGE',
  HLS_MANIFEST_FORBIDDEN: 'HLS_MANIFEST_FORBIDDEN',
  HLS_MANIFEST_NOT_FOUND: 'HLS_MANIFEST_NOT_FOUND',
  HLS_MANIFEST_TIMEOUT: 'HLS_MANIFEST_TIMEOUT',
  HLS_MANIFEST_FETCH_FAILED: 'HLS_MANIFEST_FETCH_FAILED',
  REMOTE_SOURCE_AUTHENTICATION_REQUIRED: 'REMOTE_SOURCE_AUTHENTICATION_REQUIRED',
  HLS_PLAYLIST_DEPTH_EXCEEDED: 'HLS_PLAYLIST_DEPTH_EXCEEDED',
  HLS_PLAYLIST_LOOP: 'HLS_PLAYLIST_LOOP',
  HLS_TOO_MANY_VARIANTS: 'HLS_TOO_MANY_VARIANTS',
  HLS_TOO_MANY_SEGMENTS: 'HLS_TOO_MANY_SEGMENTS',
  HLS_NO_VALID_VARIANT: 'HLS_NO_VALID_VARIANT',
  HLS_SELECTED_VARIANT_NOT_FOUND: 'HLS_SELECTED_VARIANT_NOT_FOUND',
  HLS_AUDIO_TRACK_NOT_FOUND: 'HLS_AUDIO_TRACK_NOT_FOUND',
  HLS_LIVE_DURATION_REQUIRED: 'HLS_LIVE_DURATION_REQUIRED',
  HLS_LIVE_NOT_SUPPORTED: 'HLS_LIVE_NOT_SUPPORTED',
  HLS_LIVE_DURATION_INVALID: 'HLS_LIVE_DURATION_INVALID',
  HLS_SEGMENT_DOWNLOAD_FAILED: 'HLS_SEGMENT_DOWNLOAD_FAILED',
  HLS_SEGMENT_INVALID: 'HLS_SEGMENT_INVALID',
  HLS_SEGMENT_TOO_LARGE: 'HLS_SEGMENT_TOO_LARGE',
  HLS_SEGMENT_RANGE_INVALID: 'HLS_SEGMENT_RANGE_INVALID',
  HLS_MAP_DOWNLOAD_FAILED: 'HLS_MAP_DOWNLOAD_FAILED',
  HLS_KEY_DOWNLOAD_FAILED: 'HLS_KEY_DOWNLOAD_FAILED',
  HLS_ENCRYPTION_NOT_SUPPORTED: 'HLS_ENCRYPTION_NOT_SUPPORTED',
  HLS_DRM_NOT_SUPPORTED: 'HLS_DRM_NOT_SUPPORTED',
  HLS_SOURCE_CHANGED: 'HLS_SOURCE_CHANGED',
  HLS_REMUX_FAILED: 'HLS_REMUX_FAILED',
  HLS_OUTPUT_INVALID: 'HLS_OUTPUT_INVALID',
  HLS_LOCAL_PLAYLIST_INVALID: 'HLS_LOCAL_PLAYLIST_INVALID',
  HLS_MP4_STREAM_COPY_UNSUPPORTED: 'HLS_MP4_STREAM_COPY_UNSUPPORTED',
  HLS_FFMPEG_FAILED: 'HLS_FFMPEG_FAILED',
  HLS_FFMPEG_TIMESTAMP_FAILED: 'HLS_FFMPEG_TIMESTAMP_FAILED',
  HLS_CONCAT_TS_COPY_FAILED: 'HLS_CONCAT_TS_COPY_FAILED',
  HLS_AUTHENTICATED_SOURCE_UNSUPPORTED: 'HLS_AUTHENTICATED_SOURCE_UNSUPPORTED',
  // Request-context / paste-as-cURL errors (spec §28).
  REMOTE_IMPORT_CURL_INVALID: 'REMOTE_IMPORT_CURL_INVALID',
  REMOTE_IMPORT_CURL_UNSAFE_OPTION: 'REMOTE_IMPORT_CURL_UNSAFE_OPTION',
  REMOTE_IMPORT_CURL_MULTIPLE_URLS: 'REMOTE_IMPORT_CURL_MULTIPLE_URLS',
  REMOTE_IMPORT_REQUEST_CONTEXT_INVALID: 'REMOTE_IMPORT_REQUEST_CONTEXT_INVALID',
  REMOTE_IMPORT_HEADER_VALUE_INVALID: 'REMOTE_IMPORT_HEADER_VALUE_INVALID',
  REMOTE_SOURCE_ACCESS_EXPIRED: 'REMOTE_SOURCE_ACCESS_EXPIRED',
  HLS_CHILD_AUTHENTICATION_REQUIRED: 'HLS_CHILD_AUTHENTICATION_REQUIRED',
  FFMPEG_NOT_AVAILABLE: 'FFMPEG_NOT_AVAILABLE',
  FFMPEG_TIMEOUT: 'FFMPEG_TIMEOUT',
  FFPROBE_FAILED: 'FFPROBE_FAILED',
} as const

export type HlsErrorCode = (typeof HLS_ERROR_CODES)[keyof typeof HLS_ERROR_CODES]

/** Human-readable (safe) messages for the stable codes. */
export const HLS_ERROR_MESSAGES: Record<HlsErrorCode, string> = {
  HLS_DISABLED: 'HLS imports are disabled.',
  HLS_INVALID_MANIFEST: 'The source is not a valid HLS playlist.',
  HLS_MANIFEST_TOO_LARGE: 'The HLS playlist is too large.',
  HLS_MANIFEST_FORBIDDEN: 'The source server rejected access to the HLS manifest.',
  HLS_MANIFEST_NOT_FOUND: 'The HLS manifest could not be found on the source server.',
  HLS_MANIFEST_TIMEOUT: 'The HLS manifest could not be read.',
  HLS_MANIFEST_FETCH_FAILED: 'The HLS manifest could not be read.',
  REMOTE_SOURCE_AUTHENTICATION_REQUIRED: 'The source server requires authentication to access the HLS manifest.',
  HLS_PLAYLIST_DEPTH_EXCEEDED: 'The HLS playlist is nested too deeply.',
  HLS_PLAYLIST_LOOP: 'The HLS playlist references itself in a loop.',
  HLS_TOO_MANY_VARIANTS: 'The HLS master playlist has too many variants.',
  HLS_TOO_MANY_SEGMENTS: 'The HLS playlist has too many segments.',
  HLS_NO_VALID_VARIANT: 'No playable HLS variant was found.',
  HLS_SELECTED_VARIANT_NOT_FOUND: 'The selected quality is no longer available.',
  HLS_AUDIO_TRACK_NOT_FOUND: 'The selected audio track is no longer available.',
  HLS_LIVE_DURATION_REQUIRED: 'A recording duration is required for live streams.',
  HLS_LIVE_NOT_SUPPORTED: 'Live HLS streams are not supported.',
  HLS_LIVE_DURATION_INVALID: 'The recording duration is outside the allowed range.',
  HLS_SEGMENT_DOWNLOAD_FAILED: 'An HLS segment could not be downloaded.',
  HLS_SEGMENT_INVALID: 'An HLS segment was invalid or corrupt.',
  HLS_SEGMENT_TOO_LARGE: 'An HLS segment exceeds the maximum allowed size.',
  HLS_SEGMENT_RANGE_INVALID: 'An HLS segment byte range could not be downloaded.',
  HLS_MAP_DOWNLOAD_FAILED: 'HLS initialization data could not be downloaded.',
  HLS_KEY_DOWNLOAD_FAILED: 'The HLS encryption key could not be downloaded.',
  HLS_ENCRYPTION_NOT_SUPPORTED: 'This HLS encryption method is not supported.',
  HLS_DRM_NOT_SUPPORTED: 'DRM-protected HLS streams are not supported.',
  HLS_SOURCE_CHANGED: 'The HLS playlist changed and the import must be restarted.',
  HLS_REMUX_FAILED: 'The HLS media could not be converted.',
  HLS_OUTPUT_INVALID: 'The converted output failed verification.',
  HLS_LOCAL_PLAYLIST_INVALID: 'The generated local playlist failed validation.',
  HLS_MP4_STREAM_COPY_UNSUPPORTED: 'This stream cannot be remuxed to MP4 using stream copy. Try MKV.',
  HLS_FFMPEG_FAILED: 'FFmpeg could not convert the media.',
  HLS_FFMPEG_TIMESTAMP_FAILED: 'FFmpeg could not fix the media timestamps.',
  HLS_CONCAT_TS_COPY_FAILED: 'FFmpeg could not convert the media by joining the segments.',
  HLS_AUTHENTICATED_SOURCE_UNSUPPORTED: 'This HLS resource requires authentication that 9Drive does not forward.',
  REMOTE_IMPORT_CURL_INVALID: 'The pasted cURL command could not be parsed.',
  REMOTE_IMPORT_CURL_UNSAFE_OPTION: 'The pasted cURL command uses an option that is not supported.',
  REMOTE_IMPORT_CURL_MULTIPLE_URLS: 'Paste a cURL command with a single URL.',
  REMOTE_IMPORT_REQUEST_CONTEXT_INVALID: 'The request context is invalid.',
  REMOTE_IMPORT_HEADER_VALUE_INVALID: 'A request context value is invalid.',
  REMOTE_SOURCE_ACCESS_EXPIRED: 'The source URL or request context may have expired. Capture a fresh media request and try again.',
  HLS_CHILD_AUTHENTICATION_REQUIRED: 'An HLS child resource requires different access credentials. Use the source host for all media or capture a fresh request.',
  FFMPEG_NOT_AVAILABLE: 'FFmpeg is not available on the server.',
  FFMPEG_TIMEOUT: 'FFmpeg exceeded its time limit.',
  FFPROBE_FAILED: 'The output could not be verified.',
}
