import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import http from 'node:http'
import type { AddressInfo } from 'node:net'
import { spawn } from 'node:child_process'
import fsp from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import type { Job } from 'bullmq'
import { prisma } from '../../config/prisma.js'
import { processRemoteImportJob } from './processor.js'
import type { RemoteImportJobData } from './queue.js'
import { AppError } from '../../utils/app-error.js'
import { hlsJobDir, readResumeMarker } from './hls/job-dir.js'
import { tempDir } from './temp-storage.js'

/**
 * End-to-end HLS remote-import test (§31 of the spec — the controlled
 * `*.m3u8` fixture must flow probe → variant → segment → local playlist →
 * FFmpeg → ffprobe → upload → registration).
 *
 * A real local HTTP fixture serves a master playlist with two variants, the
 * selected media playlist, MPEG-TS segments (generated by FFmpeg) and an
 * AES-128 key. The REAL `processRemoteImportJob` runs the HLS pipeline:
 * fetch+parse manifest, resolve the variant, materialize segments, write the
 * rewritten local playlist, run FFmpeg remux with `-protocol_whitelist
 * file,crypto`, ffprobe-verify, then upload (S3 branch mocked) and register
 * (prisma mocked). Everything except storage/Db is exercised for real.
 *
 * Requires FFmpeg on PATH (the worker container has it; the host may not).
 * Skipped cleanly when missing.
 */
const hasFfmpeg = () =>
  new Promise<boolean>((resolve) => {
    const child = spawn('ffmpeg', ['-version'], { stdio: 'ignore' })
    child.on('error', () => resolve(false))
    child.on('close', (code) => resolve(code === 0))
  })

// The fixture lives on 127.0.0.1, which the SSRF blocklist (correctly) refuses.
// As in url-downloader.test.ts, mock only the DNS + validation boundary — the
// real downloader's redirect/streaming/timeout logic stays fully real, and the
// socket still opens to the validated (loopback) address.
const validationSpy = vi.hoisted(() => ({
  validateRemoteUrl: vi.fn(),
  resolveAndValidateHost: vi.fn(),
}))

vi.mock('./ssrf.js', async (importOriginal) => {
  const actual = await importOriginal<typeof import('./ssrf.js')>()
  return {
    ...actual,
    validateRemoteUrl: validationSpy.validateRemoteUrl,
    resolveAndValidateHost: validationSpy.resolveAndValidateHost,
  }
})

// ── FFmpeg boundary: delegate to the REAL ffmpeg by default, but let a test
// force a failure (remux/re-encode) via `ffmpegFailures`. vitest gives every
// importer the SAME mocked module record here — `importOriginal` keeps the
// real binaries, the flags swap in a failing implementation.
const ffmpegFailures = vi.hoisted(() => ({ remux: false, reencode: false, reencodeCalls: 0 }))

vi.mock('./hls/ffmpeg.js', async (importOriginal) => {
  const actual = await importOriginal<typeof import('./hls/ffmpeg.js')>()
  return {
    ...actual,
    runFfmpegRemux: async (...args: Parameters<typeof actual.runFfmpegRemux>) => {
      if (ffmpegFailures.remux) throw new AppError('HLS_REMUX_FAILED', 'The HLS media could not be converted.', 502)
      return actual.runFfmpegRemux(...args)
    },
    runFfmpegReencode: async (...args: Parameters<typeof actual.runFfmpegReencode>) => {
      ffmpegFailures.reencodeCalls += 1
      if (ffmpegFailures.reencode) throw new AppError('HLS_REMUX_FAILED', 'The HLS media could not be converted.', 502)
      return actual.runFfmpegReencode(...args)
    },
  }
})

// ── Prisma mock: the pipeline writes progress + registers the file. ──────────
const uploaded = { providerFileId: 's3-key-' + Date.now(), fileId: null }
const createdFile = { id: 'file-' + Date.now(), providerFileId: '', name: '' }

vi.mock('../../config/prisma.js', () => ({
  prisma: {
    remoteImport: {
      findUnique: vi.fn(async ({ where }: { where: { id: string } }) => mockRow(where.id)),
      update: vi.fn(async ({ data }: { data: any }) => ({ ...mockRow(data.id), ...data, status: data.status ?? 'processing' })),
    },
    folder: {
      findFirst: vi.fn(async () => null),
    },
    connectedAccount: {
      findUniqueOrThrow: vi.fn(async () => ({ id: 'acc-1', provider: 's3' })),
    },
    file: {
      findFirst: vi.fn(async () => null),
      create: vi.fn(async ({ data }: { data: any }) => {
        createdFile.providerFileId = data.providerFileId
        createdFile.name = data.name
        return { ...createdFile, sizeBytes: data.sizeBytes }
      }),
      update: vi.fn(async ({ data }: { data: any }) => {
        // The S3 branch first creates a 'pending' provisional file, then
        // updates it with the REAL providerFileId — record that final value.
        if (data.providerFileId && data.providerFileId !== 'pending') createdFile.providerFileId = data.providerFileId
        return { ...createdFile, ...data }
      }),
    },
  },
}))

// Mock the storage boundary so the test never touches S3/Google. The HLS path
// uploads through `uploadTempFile`, whose S3 branch calls these.
vi.mock('../s3/s3.service.js', () => ({
  getS3ConfigForAccount: vi.fn(async () => ({ bucket: 'test', region: 'us-east-1' })),
  uploadS3Object: vi.fn(async () => undefined),
  // The REAL buildS3ObjectKey is SYNC (returns a string) and the processor
  // calls it WITHOUT await — an async mock would hand the caller a Promise.
  buildS3ObjectKey: vi.fn(() => 'provider/object-key.mkv'),
  syncS3Quota: vi.fn(async () => undefined),
  getS3PresignedUrl: vi.fn(async () => ''),
}))

vi.mock('../uploads/storage-routing.service.js', () => ({
  selectAccount: vi.fn(async () => ({ id: 'acc-1', provider: 's3' })),
}))

vi.mock('../google/google.service.js', () => ({
  ensureGoogleAppFolder: vi.fn(async () => 'app-folder'),
  getAuthedGoogleClient: vi.fn(async () => ({})),
  syncGoogleQuota: vi.fn(async () => undefined),
}))

vi.mock('../../utils/audit.js', () => ({
  createAuditLog: vi.fn(async () => undefined),
}))

// A row that stays "queued" — the worker's cancel-poll and stage checks read
// it; the pipeline must run to completion.
function mockRow(id: string) {
  return {
    id,
    userId: 'user-1',
    folderId: null,
    connectedAccountId: 'acc-1',
    fileName: 'movie.m3u8',
    mimeType: 'application/vnd.apple.mpegurl',
    sourceType: 'hls_master',
    hlsVariantId: null,
    hlsAudioTrackId: null,
    hlsOutputContainer: 'auto',
    hlsIsLive: false,
    hlsRecordingDurationSeconds: null,
    sourceUrlEncrypted: '',
    status: 'queued',
    stage: 'waiting',
    totalBytes: null,
    downloadedBytes: 0n,
    uploadedBytes: 0n,
  }
}

let server: http.Server
let baseUrl: string
let fixtureDir: string
let masterBody = ''
let mediaBody = ''
let segment0Bytes: Buffer
let segment1Bytes: Buffer

const MASTER = () => `#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360,CODECS="avc1.4d001e,mp4a.40.2"
${baseUrl}/360.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3000000,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
${baseUrl}/720.m3u8`

function makeMediaPlaylist(segments: string[]) {
  return `#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="${baseUrl}/key.bin"
${segments.map((s) => `#EXTINF:4.000,\n${s}`).join('\n')}
#EXT-X-ENDLIST`
}

async function generateFixture() {
  fixtureDir = await fsp.mkdtemp(path.join(os.tmpdir(), '9drive-hls-fixture-'))
  const key = Buffer.from('0123456789abcdef0123456789abcdef') // 16 raw bytes
  await fsp.writeFile(path.join(fixtureDir, 'key.bin'), key)

  // FFmpeg's `-hls_key_info_file` is a TEXT file: line 1 = the key URI to
  // embed in the playlist, line 2 = the absolute path of the raw 16-byte key
  // binary. Passing the raw key bytes directly (as the previous attempt did)
  // makes FFmpeg read garbage for line 1 and an empty key — hence
  // "Nothing was written into output file".
  const keyInfoPath = path.join(fixtureDir, 'key.info')
  await fsp.writeFile(keyInfoPath, `key.bin\n${path.join(fixtureDir, 'key.bin')}\n`)

  // Use FFmpeg's HLS muxer with `-hls_key_info_file` to produce TWO AES-128
  // encrypted segments (the muxer splits at the keyframe/segment boundary and
  // encrypts each with the given key, IV derived from the segment number).
  // `-force_key_frames 0:2,0:4,0:6` pins IDR boundaries so the 8s source
  // actually splits into 2×4s segments (otherwise the ultralow-bitrate
  // encoder emits a single keyframe and the whole source collapses into one
  // segment, and seg1.ts never exists).
  await runFfmpeg([
    '-f', 'lavfi', '-i', 'testsrc=duration=8:size=640x360:rate=25',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=8',
    '-c:v', 'libx264', '-preset', 'ultrafast',
    '-force_key_frames', '0:2,0:4,0:6',
    '-c:a', 'aac', '-f', 'hls',
    '-hls_time', '4', '-hls_playlist_type', 'vod',
    '-hls_segment_filename', path.join(fixtureDir, 'seg%d.ts'),
    '-hls_key_info_file', keyInfoPath,
    path.join(fixtureDir, 'fixture.m3u8'),
  ])
  segment0Bytes = await fsp.readFile(path.join(fixtureDir, 'seg0.ts'))
  segment1Bytes = await fsp.readFile(path.join(fixtureDir, 'seg1.ts'))
}

function runFfmpeg(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn('ffmpeg', args, { stdio: ['ignore', 'pipe', 'pipe'] })
    let stderr = ''
    child.stderr?.on('data', (c: Buffer) => { stderr += c.toString() })
    child.on('error', reject)
    child.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`ffmpeg failed (${code}): ${stderr.slice(-500)}`))))
  })
}

beforeAll(async () => {
  if (!(await hasFfmpeg())) {
    console.warn('Skipping HLS integration test: ffmpeg not on PATH.')
    return
  }
  // Loopback fixture: validate the URL structurally and pass the host through
  // (the IP is loopback, which the real blocklist would refuse).
  validationSpy.validateRemoteUrl.mockImplementation(async (raw: string) => new URL(raw))
  validationSpy.resolveAndValidateHost.mockImplementation(async (host: string) => host)
  await generateFixture()
  server = http.createServer((req, res) => {
    const pathname = new URL(req.url ?? '/', 'http://x').pathname
    if (pathname === '/master.m3u8') {
      res.writeHead(200, { 'Content-Type': 'application/vnd.apple.mpegurl' })
      res.end(masterBody)
      return
    }
    if (pathname === '/720.m3u8' || pathname === '/360.m3u8') {
      res.writeHead(200, { 'Content-Type': 'application/vnd.apple.mpegurl' })
      res.end(mediaBody)
      return
    }
    // The media playlist references seg0.ts / seg1.ts — serve the REAL bytes
    // of each (each segment is AES-128 encrypted with a distinct IV, so a
    // segment must be served by its own ciphertext).
    if (pathname === '/seg0.ts') {
      res.writeHead(200, { 'Content-Type': 'video/mp2t' })
      res.end(segment0Bytes)
      return
    }
    if (pathname === '/seg1.ts') {
      res.writeHead(200, { 'Content-Type': 'video/mp2t' })
      res.end(segment1Bytes)
      return
    }
    if (pathname === '/key.bin') {
      res.writeHead(200, { 'Content-Type': 'application/octet-stream' })
      res.end(Buffer.from('0123456789abcdef0123456789abcdef'))
      return
    }
    res.writeHead(404)
    res.end()
  })
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve))
  const { port } = server.address() as AddressInfo
  baseUrl = `http://127.0.0.1:${port}`
  // The playlist bodies embed baseUrl — build them AFTER the port is known.
  mediaBody = makeMediaPlaylist(['seg0.ts', 'seg1.ts'])
  masterBody = MASTER()
})

afterAll(async () => {
  server?.close()
  if (fixtureDir) await fsp.rm(fixtureDir, { recursive: true, force: true }).catch(() => undefined)
})

describe('HLS remote import end-to-end (fixture)', () => {
  it('flows probe → segment → playlist → FFmpeg → ffprobe → upload → register', async () => {
    if (!fixtureDir) return // skipped (no ffmpeg)
    validationSpy.validateRemoteUrl.mockReset()
    validationSpy.resolveAndValidateHost.mockReset()
    validationSpy.validateRemoteUrl.mockImplementation(async (raw: string) => new URL(raw))
    validationSpy.resolveAndValidateHost.mockImplementation(async (host: string) => host)
    const importId = 'import-hls-e2e'
    const job = { data: { importId, attempt: 1 }, id: 'job-1' } as unknown as Job<RemoteImportJobData>

    // The real source URL is encrypted by the processor at create; here the
    // mock row's sourceUrlEncrypted is empty. Patch it to the fixture URL.
    const updateMock = prisma.remoteImport.update as ReturnType<typeof vi.fn>
    updateMock.mockClear()
    prisma.remoteImport.findUnique = vi.fn(async () => mockRow(importId))

    // Wire the encrypted source URL into the row the processor decrypts.
    // `decryptText` in the processor uses TOKEN_ENCRYPTION_KEY from env — the
    // setup file provides a test key; encrypt the fixture URL with the same
    // key so decrypt succeeds.
    const { encryptText } = await import('../../utils/crypto.js')
    const row = mockRow(importId)
    row.sourceUrlEncrypted = encryptText(`${baseUrl}/master.m3u8`)
    prisma.remoteImport.findUnique = vi.fn(async () => row)

    await processRemoteImportJob(job)

    // The import must have completed: the final `update` carried status
    // 'completed' + a fileId link. The mock's factory takes a single
    // destructured `{ data }` argument, so the call args are `[{ data }]`.
    const completed = updateMock.mock.calls.some((call) => call[0]?.data?.status === 'completed')
    expect(completed).toBe(true)

    // Registration happened with the real remuxed output name. `auto` for this
    // simple fixture (no separate audio/subtitles/discontinuities) resolves to
    // MP4 — the output must carry the resolved container's extension.
    expect(createdFile.name).toMatch(/\.(mp4|mkv)$/)
    expect(createdFile.providerFileId).toContain('provider/object-key')
  })

  it('remux failure keeps the job dir + resume marker; a convert-only retry completes without re-downloading', async () => {
    if (!fixtureDir) return // skipped (no ffmpeg)
    validationSpy.validateRemoteUrl.mockReset()
    validationSpy.resolveAndValidateHost.mockReset()
    validationSpy.validateRemoteUrl.mockImplementation(async (raw: string) => new URL(raw))
    validationSpy.resolveAndValidateHost.mockImplementation(async (host: string) => host)

    const importId = 'import-hls-resume'
    const job = { data: { importId, attempt: 1 }, id: 'job-1' } as unknown as Job<RemoteImportJobData>
    const { encryptText } = await import('../../utils/crypto.js')
    const row = mockRow(importId)
    row.sourceUrlEncrypted = encryptText(`${baseUrl}/master.m3u8`)
    prisma.remoteImport.findUnique = vi.fn(async () => row)
    const updateMock = prisma.remoteImport.update as ReturnType<typeof vi.fn>
    updateMock.mockClear()

    const jobDir = hlsJobDir(row.userId, importId)
    // The run is deterministic: segments land in the job dir. Clean any
    // leftover before the first run.
    await import('node:fs/promises').then((fsp) => fsp.rm(jobDir, { recursive: true, force: true }))

    // ── Run 1: make the remux FAIL (the remux step is reached with all
    // segments materialized). The conversion chain runs remux → mkv-fallback
    // remux → re-encode, so ALL THREE must fail for the import to fail — the
    // mocked boundary (see vi.mock above) throws for both functions.
    ffmpegFailures.remux = true
    ffmpegFailures.reencode = true
    await processRemoteImportJob(job)
    ffmpegFailures.remux = false
    ffmpegFailures.reencode = false

    // The job must be marked failed with the remux error code.
    const failed = updateMock.mock.calls.some((call) => call[0]?.data?.status === 'failed' && call[0]?.data?.errorCode === 'HLS_REMUX_FAILED')
    expect(failed).toBe(true)

    // The job dir was KEPT (a resume marker exists) and the materialized
    // segments are still on disk for the convert-only retry.
    const marker = await readResumeMarker(jobDir)
    expect(marker).not.toBeNull()
    expect(marker?.mode).toBe('remux-only')
    const files = await fsp.readdir(jobDir)
    expect(files).toContain('video.m3u8')
    expect(files.some((f) => f.startsWith('video-000') && f.endsWith('.ts'))).toBe(true)

    // ── Run 2: a convert-only retry. The row is queued again (worker status
    // allows it), the marker is present, and the SAME segment files exist. The
    // fixture counts segment requests so we can assert zero re-downloads.
    let segmentRequests = 0
    const realServer = server
    // Wrap the server's existing segment handlers with a counter.
    const originalListener = realServer.listeners('request')[0] as (req: import('node:http').IncomingMessage, res: import('node:http').ServerResponse) => void
    realServer.removeAllListeners('request')
    realServer.on('request', (req, res) => {
      if (new URL(req.url ?? '/', 'http://x').pathname.startsWith('/seg')) segmentRequests += 1
      originalListener(req, res)
    })

    updateMock.mockClear()
    prisma.remoteImport.findUnique = vi.fn(async () => ({ ...row, status: 'queued' }))
    await processRemoteImportJob(job)

    // Completed AND no segment was re-requested (the cache-seeded resume reused
    // the on-disk files; only the small key.bin re-downloads).
    const completed2 = updateMock.mock.calls.some((call) => call[0]?.data?.status === 'completed')
    expect(completed2).toBe(true)
    expect(segmentRequests).toBe(0)

    // Success drops the marker, and the dir is cleaned up.
    expect(await readResumeMarker(jobDir)).toBeNull()
  })

  it('falls back to re-encode when the stream-copy remux fails, and still completes', async () => {
    if (!fixtureDir) return // skipped (no ffmpeg)
    validationSpy.validateRemoteUrl.mockReset()
    validationSpy.resolveAndValidateHost.mockReset()
    validationSpy.validateRemoteUrl.mockImplementation(async (raw: string) => new URL(raw))
    validationSpy.resolveAndValidateHost.mockImplementation(async (host: string) => host)

    const importId = 'import-hls-reencode'
    const job = { data: { importId, attempt: 1 }, id: 'job-1' } as unknown as Job<RemoteImportJobData>
    const { encryptText } = await import('../../utils/crypto.js')
    const row = mockRow(importId)
    row.sourceUrlEncrypted = encryptText(`${baseUrl}/master.m3u8`)
    prisma.remoteImport.findUnique = vi.fn(async () => row)
    const updateMock = prisma.remoteImport.update as ReturnType<typeof vi.fn>
    updateMock.mockClear()

    // The conversion chain must attempt remux, the mkv fallback, and re-encode.
    // Only the re-encode (REAL ffmpeg) is allowed to succeed.
    ffmpegFailures.remux = true
    ffmpegFailures.reencode = false
    await processRemoteImportJob(job)
    ffmpegFailures.remux = false

    // The re-encode must have run and produced a real output (the wrapper
    // delegates to the REAL ffmpeg; it only counts calls).
    expect(ffmpegFailures.reencodeCalls).toBeGreaterThan(0)
    const completed = updateMock.mock.calls.some((call) => call[0]?.data?.status === 'completed')
    expect(completed).toBe(true)
    expect(createdFile.name).toMatch(/\.(mp4|mkv)$/)
  })
})
